### ISSUE TITLE
[Question] [Improvement] RestGlobalConfig

### ISSUE THREAD

**Issue by paulsouche** [troyanskiy/rest-core#1]
Hi,

First issue that is not really one ! I was on ngx-resource and moved on rest-*. The migration was quite smooth, TypeScript helps a lot. But I had a really small problem.

In my use case, I have `string[]` queryParams for my resources filter and it was omitted during the query because of [this](https://github.com/troyanskiy/rest-core/blob/master/src/Rest.ts#L480). I set the `RestGlobalConfig.getParamsMappingType` to `RestGetParamsMappingType.Plain` and it worked like a charm.

So what do you think of
 - Set `RestGetParamsMappingType.Plain` by default instead of `null`
 - warn about missing query parameter in default case instead of silently fail
 - Don't have static config for this as I can create other Rest implementations that won't have the same queryParams resolution
 - Add documentation

Thank you for the great job anyway

**Comment by troyanskiy** [comment]
Hi!
Thanks a lot for your feedback!

> Set `RestGetParamsMappingType.Plain` by default instead of `null`

Totally agree with you

> warn about missing query parameter in default case instead of silently fail

Could you please clarify what do you mean? Do you mean the URL params which are kind of mandatory in the URL `/url/{!param}` or about query params `/url?param=23`?

> Don't have static config for this as I can create other Rest implementations that won't have the same queryParams resolution

I will add as option to `RestParams` and `RestAction` decorators

> Add documentation

Yes

Note: I think it will be more clear, if I will rename 
* `RestGlobalConfig.getParamsMappingType` -> `RestGlobalConfig.queryMappingMethod`
* `RestGetParamsMappingType` -> `RestQueryMappingMethod`

Note 2: I will add Changelog.md file

Again, thank you very much for your feedback.

**Comment by paulsouche** [comment]
> warn about missing query parameter in default case instead of silently fail

```typescript
  protected $appendQueryParams(query: { [prop: string]: string }, key: string, value: any): void {
    //...
    if (typeof value === 'object') {
      switch (RestGlobalConfig.getParamsMappingType) {
        case RestGetParamsMappingType.Plain:
          // ...
        case RestGetParamsMappingType.Bracket:
          // ...
        case RestGetParamsMappingType.JQueryParamsBracket:
          // ...
        default:
          console.warn(`Omitted QueryParam ${key} as getParamsMappingType not found. See RestGlobalConfig for help`);
      }
    }
  }
```

That's what I meant... But useless if default value.
