### ISSUE TITLE
Unexpected behavior when using only path params

### ISSUE THREAD

**Issue by blazekv** [troyanskiy/rest-core#13]
I have resource only with path param and body. According to interface and documentation everything looks OK.

```typescript
  @ResourceAction({
    method: ResourceRequestMethod.Post,
    path: '/{!invoiceId}/items/'
  })
  addItem: IResourceMethodStrict<InvoiceItem, any, {invoiceId: number}, any>;
```

But when I call resource action it did not create correct URL. I tried 
```typescript
this.invoiceResource.addItem(invoiceItem, null, {invoiceId: invoiceId});
```

I tried to debug it and found out, that the main reason is this:
```typescript
for (let i = 0; i < args.length; i++) {
        const arg = args[i];
        if (typeof arg === 'function') {
          if (onSuccess) {
            onError = arg;
          } else {
            onSuccess = arg;
          }
        } else {
          if (!body) {
            body = arg;
          } else if (!query) {
            query = arg;
          } else {
            params = arg;
          }
        }
      }
```
So when I set second parameter as null, it did not assign third param to variable params. It will assign it to query.

https://github.com/troyanskiy/ngx-resource-core/blob/master/src/ResourceAction.ts#L38

I created pull request. But I did not test it. Could you please verify that the fix is OK?

**Comment by kuhnroyal** [comment]
Same issue here.
