### ISSUE TITLE
Cannot use Array query Params

### ISSUE THREAD

**Issue by paulsouche** [troyanskiy/rest-core#15]
Hi,

Append queryParams [this way](https://github.com/troyanskiy/ngx-resource-core/blob/master/src/Resource.ts#L488) does not work.

for example, let's say I have a key `filter` with an Array value `['foo', 'bar']`. Expected queryString is `?filter=foo&filter=bar` In Plain queryMappingMethod but I get `?filter=foo,bar` ?

It worked [in @ngx-resource](https://github.com/troyanskiy/ngx-resource/blob/master/src/Resource.ts#L737)

For me, you should let value untouched in this case. It's the Handler role to create a Request that support `query: { filter: ['foo', 'bar']}`.

If you don't want to change this logic, what about a default queryMappingMethod in switch case where you set

```typescript
query[key] = value;
```

And let client handler handle it ?

Thanks anyway for the great job

**Comment by troyanskiy** [comment]
Hello.
Thank you for the issue. I will check the best solution to handle that.

**Comment by troyanskiy** [comment]
In fact, you can overwrite `$appendQueryParams` method in your base resource

``` typescript

export class BaseResource extends Resource {

  protected $appendQueryParams(query: { [p: string]: string | any[] },
                               key: string,
                               value: any, 
                               queryMappingMethod: ResourceQueryMappingMethod): void {

    if (Array.isArray(value)) {
      query[key] = value;
    } else {
      super.$appendQueryParams(query, key, value, queryMappingMethod);
    }

  }
}

```

**Comment by paulsouche** [comment]
Thank you for your quick answer

**Comment by ssi-hu-tasi-norbert** [comment]
The issue is still exist due to HttpParams:
https://github.com/angular/angular/issues/19071
I've tried with ngx-resource-handler-ngx-http. It worked with ngx-resource. A hack is required I'm afraid of.

**Comment by chulian1819** [comment]
hack is to use jQuery $.params(multidimensionalArray);
