### ISSUE TITLE
Remove body from DELETE requests

### ISSUE THREAD

**Issue by robelcik** [troyanskiy/rest-core#20]
Hello!

I have a resource action like:
```
@ResourceAction({
    path: '/{!:id}',
    method: ResourceRequestMethod.Delete,
    requestBodyType: ResourceRequestBodyType.NONE
})
deleteRecord: IResourceMethod<{id: number}, void>;
```

In this setup, the body sent to the server is '{}' (JSON literal for an empty object). I would like my request to have no body at all. Of course, I can override $setRequestOptionsBody() method but it would be nicer to have it done automatically or by resource action's configuration.

**Comment by troyanskiy** [comment]
Hello. Sorry for the delay in the fix.
You can try to update to 5.2.2
