### ISSUE TITLE
How to specify different name for 'id' field?

### ISSUE THREAD

**Issue by blingerson** [troyanskiy/rest-core#21]
Looking at the code, it does not appear possible to specify a custom id field name, for example 'uuid' instead of 'id'.  Is this actually the case, or am I missing something?

**Comment by kuhnroyal** [comment]
Use the `@ResourceAction` decorator:

```
  @ResourceAction({
    path: "/{!uuid}"
  })
```

**Comment by blingerson** [comment]
@kuhnroyal, I know how to change it in a one off as you describe, but I was wondering if there was a way to do it more globally for a specific Resource instead of re-decorating all the CRUD actions.

**Comment by kuhnroyal** [comment]
Nah, don't think that is possible. Probably just implement your own `ResourceCRUD`.

**Comment by blingerson** [comment]
That is kind of what I figured, but was hoping I was missing some decorator magic...

**Comment by blingerson** [comment]
Closing, since this is more of a feature request...
