### ISSUE TITLE
Get method for resource class?

### ISSUE THREAD

**Issue by colmben** [troyanskiy/rest-core#25]
I am trying to use the ResourceCRUD way of accessing a resource. In your example code you show : 

`const user1 = await this.userResource.get('1');`

But if I try to do this, I get a typing error. It looks like it is in fact expecting 

`const user1 = await this.userResource.get(id => '1'); `

That complies ok but gives me this error : 

`Error: Mandatory {!id} path parameter is missing`

Is it possible to GET a record without using the main model class?

Note that the reason I am trying to do it this way is that I am trying to use this inside a resolve for UI Router 2 and I can't get the User.get() way to work. The userResource.get() seems more promising but as above I can't get that working either! If you have any knowledge of using ngx-resource inside a route resolve function it would be great.

EDIT - Again I figure it out once I've posted the issue :) Should be:

`const user1 = await this.userResource.get({id:'1'}); `

And again, if you had some known working code for a real life project it would be so handy, these small syntax issues can take up hours (and possibly lead to people not using the library at all as they can't even get the example code up and running).

**Comment by troyanskiy** [comment]
Hello @all
I did some refactoring and repository restructuring.
From now on new repository is located here https://github.com/troyanskiy/ngx-resource
Please create new issues in new repo.
I will close all the issues in that repo.

Also I have released 7.0.0-beta.5 version with `Observables` support. Please test it and create new issues in new repo if you will find some bugs.

To update to new version run
`npm i --save @ngx-resource/core@beta @ngx-resource/handler-ngx-http@beta`

### Breaking changes:
#### `ResourceGlobalConfig`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

#### `IResourceParams` and `IResourceAction`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

### Deprecation
* `IResourceMethod` -> `IResourceMethodPromise`
* `IResourceMethodStrict` -> `IResourceMethodPromiseStrict`
* `IResourceMethodFull` -> `IResourceMethodPromiseFull`
* `IResourceMethodStrictFull` -> `IResourceMethodPromiseStrictFull`
* `ResourceCRUD` -> `ResourceCRUDPromise`

### New
* `ResourceCRUDObservable` - same as ResourceCRUDPromise, but typed to Observable

I still have to update Docs and provide migration guide.

Thank you @all !!!
