### ISSUE TITLE
Where is ResourceModule

### ISSUE THREAD

**Issue by tavai89** [troyanskiy/rest-core#26]
Hi, may be I am doing something wrong and question is dumb, but where is ResourceModule are located? I can't find it to import into my application module. Can you please point me what I am doing wrong.
Thank you!

**Comment by troyanskiy** [comment]
Hi
It’s in `@ngx-resource/handler-ngx-http` library.

**Comment by tavai89** [comment]
Sorry, this is not clear for :( Where can I get the Library?

**Comment by troyanskiy** [comment]
For some reason github hides part of my comment.
It here https://github.com/troyanskiy/ngx-resource-handler-ngx-http

**Comment by tavai89** [comment]
Oh, now I got it. Thank you so much for you help! You doing great job, I really like your libraries
