### ISSUE TITLE
Custom Http for library

### ISSUE THREAD

**Issue by genuinefafa** [troyanskiy/rest-core#3]
I'm currently following [this tutorial](https://scotch.io/@kashyapmukkamala/using-http-interceptor-with-angular2) to implement a main Http component so I can do my magic there.

I was using ngx-resource, but now I'm moving towards rest-* as suggested, how can I _provide_ my Http for the library? I would like to have only one Http doing the magic and not setting up different places to avoid issues.

**Comment by troyanskiy** [comment]
Hello.
Sorry for the delayed answer.
I believe you are using `Http` from `@angular/http`?
I think its really easy to replace angular's http with your custom one which, I believe you have created like `export class MyHttp extends Http`.
Simply in you ngModule in providers add provider `{provide: Http, useClass: MyHttp, deps: [ConnectionBackend, RequestOptions]}`

Hope it will help you.

**Comment by genuinefafa** [comment]
psst, it was only 6 hours! that's not delayed for me!

I'm not entirely sure, since I don't completely understand the way rest-* works. 

Does it use Http or HttpClient? I'm leaning towards HttpClient because of [this ](https://stackoverflow.com/a/45129865/1098814)

**Comment by troyanskiy** [comment]
In fact,  it's you who decide what to use.
So if you need `HttpClient` - use `rest-ngx`, if you need `Http` - use `rest-ngx-http`.

**Comment by genuinefafa** [comment]
I see... What if I use both? 🤔

**Comment by troyanskiy** [comment]
In that case, you will need to write your own `RequestHandler` which will use both `Http`and `HttpClient`
