### ISSUE TITLE
Question on getting access to headers in success callback

### ISSUE THREAD

**Issue by cschaepe** [troyanskiy/rest-core#30]
It is not clear that I can get to the response in the success callback.  I need to get to a header function to retrieve the total-count of records.  I see that I can get to the headers in the error callback but not the success.  I am trying to adapt my rest resource methods to use your api.  The different Resource Methods do not seem to pass this information back to my success callback.  Is there another way to get to the headers from one of these callbacks?

**Comment by troyanskiy** [comment]
Hello @cschaepe 

Thanks for the issue.
For now, it's not possible to get headers for the response. I will try to implement something for you today.

Will get back to you soon.

**Comment by cschaepe** [comment]
Thanks for quick response.Craig


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Raman Rasliuk <notifications@github.com> Date: 5/28/18  11:41 AM  (GMT-05:00) To: troyanskiy/ngx-resource-core <ngx-resource-core@noreply.github.com> Cc: cschaepe <craig.schaepe@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [troyanskiy/ngx-resource-core] Question on getting access to headers in success callback (#30) 
Hello @cschaepe
Thanks for the issue.

For now, it's not possible to get headers for the response. I will try to implement something for you today.
Will get back to you soon.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392557900","url":"https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392557900","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/troyanskiy/ngx-resource-core","title":"troyanskiy/ngx-resource-core","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/troyanskiy/ngx-resource-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@troyanskiy in #30: Hello @cschaepe \r\n\r\nThanks for the issue.\r\nFor now, it's not possible to get headers for the response. I will try to implement something for you today.\r\n\r\nWill get back to you soon."}],"action":{"name":"View Issue","url":"https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392557900"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [troyanskiy/ngx-resource-core] Question on getting access to headers in success callback (#30)",
"sections": [
{
"text": "",
"activityTitle": "**Raman Rasliuk**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@troyanskiy",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"troyanskiy/ngx-resource-core\",\n\"issueId\": 30,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"troyanskiy/ngx-resource-core\",\n\"issueId\": 30\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392557900"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339827812\n}"
}
],
"themeColor": "26292E"
}

**Comment by troyanskiy** [comment]
I have pushed the new version
Please check change log to see a new feature for you.

**Comment by cschaepe** [comment]
Many thanksCraig


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Raman Rasliuk <notifications@github.com> Date: 5/28/18  12:26 PM  (GMT-05:00) To: troyanskiy/ngx-resource-core <ngx-resource-core@noreply.github.com> Cc: cschaepe <craig.schaepe@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [troyanskiy/ngx-resource-core] Question on getting access to headers in success callback (#30) 
I have pushed the new version

Please check change log to see a new feature for you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392565749","url":"https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392565749","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/troyanskiy/ngx-resource-core","title":"troyanskiy/ngx-resource-core","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/troyanskiy/ngx-resource-core"}},"updates":{"snippets":[{"icon":"PERSON","message":"@troyanskiy in #30: I have pushed the new version\r\nPlease check change log to see a new feature for you."}],"action":{"name":"View Issue","url":"https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392565749"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [troyanskiy/ngx-resource-core] Question on getting access to headers in success callback (#30)",
"sections": [
{
"text": "",
"activityTitle": "**Raman Rasliuk**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@troyanskiy",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"troyanskiy/ngx-resource-core\",\n\"issueId\": 30,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/troyanskiy/ngx-resource-core/issues/30#issuecomment-392565749"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339827812\n}"
}
],
"themeColor": "26292E"
}

**Comment by cschaepe** [comment]
I had a chance to test out your changes and was successful in getting to
the headers.  Thanks for the quick changes.

**Comment by troyanskiy** [comment]
Nice!
You are welcome.
