### ISSUE TITLE
migrating resources from ngx-resource

### ISSUE THREAD

**Issue by blandialcani** [troyanskiy/rest-core#33]
Hello,

(maybe this is a duplicate of #11 but I did not understand where the modification needs to be done)

I want to migrate my resources from Ngx-resource to  Ngx-resource-core since I am upgrading to Angular 6 and Http is deprecated now. 
I want to be able to use the resources with observables instead of promises, so I won't have to modify the all the code where Ngx-resource resources are used.

After taking a look at the code of Ngx-resource-core I have noticed that in order to be compatible with Ngx-resource the Resource methods need to return observables instead of promises.

How would you suggest I can approach this issue?
Do you think converting the mainPromise property of the Resource class into an observable instead of a promise would be enough?

Thank you for your time and for the great work

**Comment by troyanskiy** [comment]
Hello @all
I did some refactoring and repository restructuring.
From now on new repository is located here https://github.com/troyanskiy/ngx-resource
Please create new issues in new repo.
I will close all the issues in that repo.

Also I have released 7.0.0-beta.5 version with `Observables` support. Please test it and create new issues in new repo if you will find some bugs.

To update to new version run
`npm i --save @ngx-resource/core@beta @ngx-resource/handler-ngx-http@beta`

### Breaking changes:
#### `ResourceGlobalConfig`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

#### `IResourceParams` and `IResourceAction`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

### Deprecation
* `IResourceMethod` -> `IResourceMethodPromise`
* `IResourceMethodStrict` -> `IResourceMethodPromiseStrict`
* `IResourceMethodFull` -> `IResourceMethodPromiseFull`
* `IResourceMethodStrictFull` -> `IResourceMethodPromiseStrictFull`
* `ResourceCRUD` -> `ResourceCRUDPromise`

### New
* `ResourceCRUDObservable` - same as ResourceCRUDPromise, but typed to Observable

I still have to update Docs and provide migration guide.

Thank you @all !!!
