### ISSUE TITLE
How to set Authorization header for Bearer tokens 

### ISSUE THREAD

**Issue by gustyn** [troyanskiy/rest-core#4]
My current project requires that I set a Bearer Token issued by IdentityServer4 in my .net core/angular solution.

However, I am having trouble getting the header into the @RestParams decorator because the access_token I need is not available until after I authenticate with my IdentityServer.

My latest attempt is to have a separate config class with static functions as such:

```ts
import { Observable } from 'rxjs/Observable';
export class AccountResourceConfig {
  public static authHeader: any;
  public static setAuthorizationHeader(header: Observable<string>) {
    header.subscribe(authHeader => AccountResourceConfig.authHeader = {Authorization: authHeader});

  }

}
```

Then I reference it as such in my Resource file:
```ts
import { Observable } from 'rxjs/Observable';
import { IRestParamsBase } from 'rest-core/src/Declarations';
import { apiAccountPrefix, apiRoot } from '../../../config/constants';
import { Injectable } from '@angular/core';
import { Rest, RestParams, RestAction, IRestMethod, RestRequestMethod, IRestMethodStrict, RestHandler } from 'rest-core';
import { IAccount } from '../models/IAccount.interface';
import { AccountQuery } from '../models/AccountQuery.model';
import { AccountListItem } from '../models/AccountListItem.model';
import { RestHandlerHttpClient } from 'rest-ngx';
import { AccountResourceConfig } from '../models/AccountResourceConfig.model';

@Injectable()
@RestParams({
  // IRestParams
  pathPrefix: apiAccountPrefix,
  url: apiRoot,
  headers: {Authorization: typeof this.authorizationHeader !== 'undefined' ? this.authorizationHeader : 'Bearer'}
})
export class AccountResource extends Rest {
  public authorizationHeaderSource: Observable<string> = new Observable<string>();
  private authorizationHeader: string;
  @RestAction({
    path: '/{!id}',
  })
  getAccount: IRestMethod<{id: string}, IAccount>;

  @RestAction({
    expectJsonArray: true,
   })
  getAccountList: IRestMethod<{id: string}, AccountListItem[]>;

  // @RestAction({
  //   method: RestRequestMethod.Post
  // })
  // createAccount: IRestMethodStrict<IAccount, AccountQuery, IAccountPathParams, IAccount>;

  constructor(restHandler: RestHandler) {
    super(restHandler);

  }

}
```
The only thing getting dropped into the authorization header is "Bearer" which means the observable is not working.  Any pointers?  I am still relatively new to TS/JS so it has to be something simple.

**Comment by troyanskiy** [comment]
Hello.
How do you receive the `access_token`.
Is it in the body of the specific request or in the header?

**Comment by gustyn** [comment]
It comes across as a query string that is sent back to my callback url as a get.

`location:http://localhost:50728/login#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImNiZDk4MDJkNzg4MGZiODAwMjNjYWM1MWMyMGZmZDBmIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MDk2MjM0MjAsImV4cCI6MTUwOTYyMzcyMCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTciLCJhdWQiOiJqc19vaWRjIiwibm9uY2UiOiJ6UnlLcnNqNjF4QzJQYk9aWDdXTmNlaGswSEp4T3N0NlJGd204SmNvIiwiaWF0IjoxNTA5NjIzNDIwLCJhdF9oYXNoIjoidjRqNFVKNGVXN0ZYcDdvWTZhMUxiQSIsInNpZCI6ImY0NDlmMjZjMzU3YjU2Yjg5YzI4YWY0MDkyMGZjNDg5Iiwic3ViIjoiNDU5NjQxNGUtN2FhMS00NjRjLWY4YmUtMDhkNTIxZTc0NzM4IiwiYXV0aF90aW1lIjoxNTA5NjIzNDIwLCJpZHAiOiJsb2NhbCIsIm5hbWUiOiJhbGljZSIsImFtciI6WyJwd2QiXX0.bU_6Jy56K81Ldz7HqN4jmm3xgaQV0NqP5muQENUudJ66MlfNOYI8ELI28whyihWvBQXahaz2NWh7GfTqEw8uNleivXCBJQXLa_MwJXG4svc6dtMIfx3A39wgUP0XTpNVLxyJbTXK3x9nrDJCht_dRWCMC1Fg00uFd7NbMKAX83rjg51USJgepJpUEDenwc3OrPIceHEIbIp6uWl7TINOmr7FEptL1A37UtF98sHzDKCWRZSOY9TLzN8EiXwVcIH0Iv8TFlHotWclrLlcE-diLNHvMAipwUK2Za2ctq9WTKv-lsxrpFG4-N3Ph74gEuIH9jN6h_0DuoXKzbGK3YpEqQ&access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImNiZDk4MDJkNzg4MGZiODAwMjNjYWM1MWMyMGZmZDBmIiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MDk2MjM0MjAsImV4cCI6MTUwOTYyNzAyMCwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTciLCJhdWQiOlsiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzOTcvcmVzb3VyY2VzIiwiaHJhIl0sImNsaWVudF9pZCI6ImpzX29pZGMiLCJzdWIiOiI0NTk2NDE0ZS03YWExLTQ2NGMtZjhiZS0wOGQ1MjFlNzQ3MzgiLCJhdXRoX3RpbWUiOjE1MDk2MjM0MjAsImlkcCI6ImxvY2FsIiwibmFtZSI6ImFsaWNlIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwiaHJhIl0sImFtciI6WyJwd2QiXX0.aqUPkmSyRdqALU7sT54MFBf4S6x6LE4BXHAwjEwFRwvrQPJMvg8mEWme1LDFkl5RvGRoUmAzxeF6bPgek9CVphm0KA10IvQJAZYMB1OgHY_F3y_LiWTOpEjRP2SUt6sGdprssivMJrRsbDXQpwKfAsgi0IQnpz4ERioZUFQ_T14d4f01iFxJ56fcDVKy_0Ts_NCaAgcxB07QJiMT8zEVzH27a3ALAIAyYH3TT7AzdRs7rbpOQ38Qada2ygxNcYLTJjnhVlE_Z8vs9cNFGz8liyJbGQpx1uo3BudMVH7CTvUzkyzGUFNQbfUj9vAl_ZyyeCj4u-TasOG3tG2ShZNo0g&token_type=Bearer&expires_in=3600&scope=openid%20profile%20email%20hra&state=zRyKrsj61xC2PbOZX7WNcehk0HJxOst6RFwm8Jco&session_state=akxStSVVYse1H9_LhG9uJVZQO-FQ4hObH0a5RZZZZ6c.0ef6628bf352efa28ed5bcd3556db41c`

**Comment by gustyn** [comment]
Additional Info:  I am using npm package angular-oauth2-oidc to authenticate with our ID4 server

**Comment by troyanskiy** [comment]
So.. I don't have time to dig how does your Auth Service works...
There are multiple ways to set headers
1. Set with `RestGlobalConfig. headers = {'header: 'hello'};`
2. Overwrite `getHeaders()` method in your rest file, so you can create some kind of `BaseRest` with overwritten `getHeaders` and extend your main `rest` classes with `BaseRest`

**Comment by gustyn** [comment]
OK thanks for the pointers.  I did not expect you to dig into the package, just provided the info in case you already knew the package.

**Comment by gustyn** [comment]
Thanks a lot for your help.  I was able to do this finally by overriding the $getHeader function as you suggested:

`$getHeaders(actionOptions?: IRestAction): any | Promise<any> {
    console.log('in getHeaders');
    if (actionOptions.headers) {
      console.log('actionOptions.headers is good');
      if (this.authHeader) {
        actionOptions.headers = actionOptions.headers.set('Authorization', this.authHeader);
      }
    } else {
      actionOptions.headers = new HttpHeaders();
      if (this.authHeader) {
        actionOptions.headers = [{'Authorization': this.authHeader}];
      }
    }
    console.log(actionOptions.headers);
    return actionOptions.headers;
  }
}
`

Thanks for the help.
