### ISSUE TITLE
Post/Put array with pathparam

### ISSUE THREAD

**Issue by ssi-hu-tasi-norbert** [troyanskiy/rest-core#40]
Hello,

I'd like to call method with path params and send an array. So I've tried:

`    @ResourceAction({
        method: ResourceRequestMethod.Put,
        path: '/sources/{!id}/parameters'
    })
    updateSourceParameters: IResourceMethodStrict<any, any, any, any>;
`
or IResourceMethodStrict, but the body is always empty.
The call itself:

`this.service.updateSourceParameters(this.current.parameters, null, {  id: this.current.object.id });`

The pathparameter is replaced as it hast to be.

Thank you

**Comment by troyanskiy** [comment]
Hello @ssi-hu-tasi-norbert 
Just tested your case and it's ok for me (array sent)

Can you specify more details?

Thanks.

**Comment by ssi-hu-tasi-norbert** [comment]
I use mobx-angular and for what reason it is cause the issue somehow. In every other case it works as expected. I've had to convert it before the call.

Thank you for your quick response!
