### ISSUE TITLE
My fork for Node.js

### ISSUE THREAD

**Issue by Serabass** [troyanskiy/rest-core#43]
Hi!
I saw the line `@ngx-resource/handler-fetch. Besed on Fetch API. Not yet created.`, forked this project and rewrited for Node.js. It uses a Fetch API and can be useful for some cases.

Link: https://github.com/Serabass/ngx-resource-core

Example: `node -r ts-node/register sandbox.ts`

Though it's not related to Angular and I think how must it'll be named.

It may be useful. Or not :)

**Comment by troyanskiy** [comment]
Hello @all
I did some refactoring and repository restructuring.
From now on new repository is located here https://github.com/troyanskiy/ngx-resource
Please create new issues in new repo.
I will close all the issues in that repo.

Also I have released 7.0.0-beta.5 version with `Observables` support. Please test it and create new issues in new repo if you will find some bugs.

To update to new version run
`npm i --save @ngx-resource/core@beta @ngx-resource/handler-ngx-http@beta`

### Breaking changes:
#### `ResourceGlobalConfig`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

#### `IResourceParams` and `IResourceAction`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

### Deprecation
* `IResourceMethod` -> `IResourceMethodPromise`
* `IResourceMethodStrict` -> `IResourceMethodPromiseStrict`
* `IResourceMethodFull` -> `IResourceMethodPromiseFull`
* `IResourceMethodStrictFull` -> `IResourceMethodPromiseStrictFull`
* `ResourceCRUD` -> `ResourceCRUDPromise`

### New
* `ResourceCRUDObservable` - same as ResourceCRUDPromise, but typed to Observable

I still have to update Docs and provide migration guide.

Thank you @all !!!

**Comment by troyanskiy** [comment]
Hi @Serabass 

Thanks you for your development.

I have build and published beta version of RequestHandler based on fetch which is a bit based on your code.

https://github.com/troyanskiy/ngx-resource/tree/master/projects/ngx-resource/handler-fetch

Would you like to test it?
`npm i --save @ngx-resource/core @ngx-resource/handler-ngx-http @ngx-resource/handler-fetch@beta`

Thanks a lot!
