### ISSUE TITLE
toObservable support

### ISSUE THREAD

**Issue by httpete** [troyanskiy/rest-core#49]
Hi, I see that commented out - can that be enabled?  Everyone wants an observable returned instead of promise.

**Comment by troyanskiy** [comment]
Hello @all
I did some refactoring and repository restructuring.
From now on new repository is located here https://github.com/troyanskiy/ngx-resource
Please create new issues in new repo.
I will close all the issues in that repo.

Also I have released 7.0.0-beta.5 version with `Observables` support. Please test it and create new issues in new repo if you will find some bugs.

To update to new version run
`npm i --save @ngx-resource/core@beta @ngx-resource/handler-ngx-http@beta`

### Breaking changes:
#### `ResourceGlobalConfig`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

#### `IResourceParams` and `IResourceAction`
* removed `asPromise` and `asResourceResponse`
* added `returnAs` with enum type `ResourceActionReturnType`; Default is `ResourceActionReturnType.Observable`

### Deprecation
* `IResourceMethod` -> `IResourceMethodPromise`
* `IResourceMethodStrict` -> `IResourceMethodPromiseStrict`
* `IResourceMethodFull` -> `IResourceMethodPromiseFull`
* `IResourceMethodStrictFull` -> `IResourceMethodPromiseStrictFull`
* `ResourceCRUD` -> `ResourceCRUDPromise`

### New
* `ResourceCRUDObservable` - same as ResourceCRUDPromise, but typed to Observable

I still have to update Docs and provide migration guide.

Thank you @all !!!

**Comment by httpete** [comment]
Starting to test now @troyanskiy  - thank you. First thing I am hitting is how to configure it globally (as to not break all the promises based invocations)

**Comment by troyanskiy** [comment]
Thank you for testing.

You can check how to configure here https://github.com/troyanskiy/ngx-resource/issues/151

**Comment by httpete** [comment]
This is a non standard way to configure a module, a better way would be to have a provider that sets the config, that’s pretty standard if you see things like angular ui router

**Comment by troyanskiy** [comment]
@httpete 
I will implement something new for that.

Thanks for remark.
