### ISSUE TITLE
IResourceMethodPromiseStrict returns observable instead of promise

### ISSUE THREAD

**Issue by trinopoty** [troyanskiy/rest-core#50]
I recently updated to the latest version of the library and noticed this issue.
I've changed all my `IResourceMethodStrict` to `IResourceMethodPromiseStrict` but it returns an Observable instead of a Promise.
As such, I'm getting errors like `.then is not a function`.

**Comment by troyanskiy** [comment]
Hi!
Add somewhere at app initialisation to make it work globally
```typescript
ResourceGlobalConfig.returnAs = ResourceActionReturnType.Promise
```

Suggest to put that in `app.component` `constructor`

**Comment by trinopoty** [comment]
But this is still a bug.
`returnAs` should not be overriding `IResourceMethodPromiseStrict`.
If I specified a `IResourceMethodPromiseStrict`, it should return a promise and not anything else.

**Comment by troyanskiy** [comment]
`IResourceMethodPromiseStrict` is just an Interface which is used in order to tell your IDE that it should return promise

**Comment by trinopoty** [comment]
I see.
