### ISSUE TITLE
request is pending and takes exactly 59 seconds to finish

### ISSUE THREAD

**Issue by evgenyfedorenko** [troyanskiy/rest-core#7]
I am still using ngx-resource but I figured rest-core is mostly the same under to hood.
This is very weird issue I have - the GET request is pending sometimes and takes 59seconds to finish. If angular http service is called the issue does not happen. I was thinking maybe anybody encountered with something similar - please help if so.

**Comment by troyanskiy** [comment]
The best is to have somewhere repo to debug the behavior.
I did not have the issue with my projects (i'm using HttpClient)...

**Comment by evgenyfedorenko** [comment]
yeah when using bare angular HttpClient it works fine.
The problem is that this issue seems not to be related to the client - I thought it was pending because of the server slowness or something - however when not calling apis via ngx-resource it does not happen. Not sure how to debug to be honest since request is issued fine and then it is pending and client is waiting for response and that takes looong time.

**Comment by troyanskiy** [comment]
Can you create a small project, so I can try to debug the problem?

**Comment by evgenyfedorenko** [comment]
I would love to - however it does not happen all the time. I think you can close the issue - don't think there is a way to replicate the issue in your environment

**Comment by troyanskiy** [comment]
I would glad to help you...
Feel free to reopen if you will have more details.

**Comment by evgenyfedorenko** [comment]
I think this issue may be related to the way I load data in component - I use CanActivate guards which make sure component is not created before data received from the server. On top on that I use ngrx store which complicates this things a bit. When I move event dispatchers to load data in constructors of components and not in guards it seems to work. Any idea why canActivate may conflict with ng resource ?

**Comment by troyanskiy** [comment]
I'm also using canActivate guards which are waiting for some permissions from a server. And I did not have problems with that.
Can you drop here your CanActivate class?

**Comment by evgenyfedorenko** [comment]
I apologize I can not share the code but the idea is that I have 3 guards which I load one by one in router setup. But the 3rd one waits until first two are finished so I subscribe to the store and only fire the request when data is available from first two requests. I will try to rewrite it in a some more straight forward way.

**Comment by evgenyfedorenko** [comment]
Just wanted to give you a heads up that it turned out to be a server issue as I suspected. Thanks for help
