### ISSUE TITLE
Array Query parameters not working

### ISSUE THREAD

**Issue by kuhnroyal** [troyanskiy/rest-core#9]
Query parameters that are arrays are not working like they did with ngx-resource.

They always get overwritten with the last value in the array:
https://github.com/troyanskiy/rest-core/blob/master/src/Rest.ts#L490

**Comment by troyanskiy** [comment]
Hello. Sorry for the delay in the fix.
Now it will send you key=val1,val2,val4...

**Comment by kuhnroyal** [comment]
Works, thanks for the quick fix!
In the future some people may require array params as multiple: `key=val1&key=val2&key=val3`, I know some frameworks expect this.

Maybe make it configurable at some point, I think it worked that way in ngx-resource.
